Repository theQRL/block-explorer, pull requests merged in 2018-07, with the labels that each got.

#145 Add mining pool information into lastblocks component
  .meteor/.finished-upgraders
  .meteor/packages
  .meteor/release
  .meteor/versions
  imports/startup/client/mining-pools.js
  imports/startup/server/cron.js
  imports/ui/components/lastblocks/lastblocks.html
  imports/ui/components/lastblocks/lastblocks.js
  imports/ui/stylesheets/overrides.css
  package-lock.json
  package.json
Labels: Status: Completed, Type: Enhancement

#147 Add mining pool information into lastblocks component (#146)
  .meteor/.finished-upgraders
  .meteor/packages
  .meteor/release
  .meteor/versions
  development.json
  imports/startup/both/index.js
  imports/startup/client/mining-pools.js
  imports/startup/server/cron.js
  imports/startup/server/index.js
  imports/ui/components/address/address.html
  imports/ui/components/address/address.js
  imports/ui/components/lastblocks/lastblocks.html
  imports/ui/components/lastblocks/lastblocks.js
  imports/ui/components/lasttx/lasttx.html
  imports/ui/components/lasttx/lasttx.js
  imports/ui/components/lastunconfirmedtx/lastunconfirmedtx.html
  imports/ui/components/lastunconfirmedtx/lastunconfirmedtx.js
  imports/ui/components/tx/tx.html
  imports/ui/components/tx/tx.js
  imports/ui/stylesheets/overrides.css
  package-lock.json
  package.json
Labels: Status: Completed, Type: Enhancement

#149 Displays Coinbase Tx in address page with correct units
  imports/startup/client/mining-pools.js
  imports/startup/server/index.js
Labels: Priority: High, Status: Completed, Type: Bug

#157 Fixes "Mined by..." line UI glitch
  imports/ui/components/lastblocks/lastblocks.html
  imports/ui/stylesheets/overrides.css
  package-lock.json
Labels: Priority: Low, Status: Completed, Type: Bug

#160 Fixes "Mined by..." line UI glitch (#157) (#159)
  imports/ui/components/lastblocks/lastblocks.html
  imports/ui/stylesheets/overrides.css
  package-lock.json
Labels: Priority: Low, Status: Completed, Type: Bug

#165 Fix token transfers in address pages (#164)
  imports/startup/both/index.js
  imports/startup/client/mining-pools.js
  imports/startup/server/cron.js
  imports/startup/server/index.js
  imports/ui/components/address/address.html
Labels: Priority: High, Status: Completed, Type: Bug

#161 Update pools
  imports/startup/client/mining-pools.js
Labels: Priority: Low, Status: Revision Needed, Type: Maintenance

#175 Adding Minilaro pool into mainnet branch, Bugfix for address txn link
  imports/startup/client/mining-pools.js
  imports/startup/server/index.js
Labels: Status: On Hold
