Repository theQRL/block-explorer, pull requests merged in 2018-12, with the labels that each got.

#216 Update latest blocks pane
  imports/startup/server/cron.js
  imports/ui/components/lastblocks/lastblocks.html
  imports/ui/components/lastblocks/lastblocks.js
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#220 Better status area reactivity
  .meteor/packages
  .meteor/release
  .meteor/versions
  imports/api/index.js
  imports/ui/components/status/status.js
  package-lock.json
  package.json
Labels: Type: Bug

#235 Add plain text emission route for CMC
  imports/startup/server/cron.js
Labels: Type: Enhancement

#236 Add plain text emission route for CMC
  imports/startup/server/cron.js
Labels: Type: Enhancement

#237 Add plain text emission route for CMC
  imports/startup/server/cron.js
Labels: Type: Enhancement

#238 Fix caching of unconfirmed transactions, mobile fixes and some UI tweaks
  imports/startup/server/cron.js
  imports/startup/server/index.js
  imports/ui/components/address/address.html
  imports/ui/stylesheets/overrides.css
Labels: Priority: High, Status: Completed, Type: Bug

#240 Fix caching of unconfirmed transactions, mobile fixes and some UI tweaks
  imports/startup/server/cron.js
  imports/startup/server/index.js
  imports/ui/components/address/address.html
  imports/ui/stylesheets/overrides.css
Labels: Priority: High, Status: Completed, Type: Bug

#244 Version bump
  imports/startup/both/index.js
  imports/ui/components/address/address.html
  imports/ui/stylesheets/overrides.css
  package.json
Labels: Priority: Low, Type: Maintenance

#247 Cache and visual updates
  imports/startup/server/index.js
  imports/ui/components/address/address.js
  imports/ui/components/lasttx/lasttx.js
  imports/ui/components/tx/tx.html
  imports/ui/stylesheets/overrides.css
Labels: Priority: High, Status: Completed, Type: Bug

#248 Add further API routes for CC
  .eslintrc.yml
  imports/startup/client/index.js
  imports/startup/server/cron.js
  imports/startup/server/index.js
Labels: Priority: High, Status: Completed, Type: Enhancement

#249 Add further API routes for CC
  .eslintrc.yml
  imports/startup/client/index.js
  imports/startup/server/cron.js
  imports/startup/server/index.js
Labels: Priority: High, Status: Completed, Type: Enhancement

#250 Add further API routes for CC
  .eslintrc.yml
  imports/startup/client/index.js
  imports/startup/server/cron.js
  imports/startup/server/index.js
Labels: Priority: High, Status: Completed, Type: Enhancement

#252 Add mining pool
  imports/startup/client/mining-pools.js
Labels: Priority: Low, Status: Completed, Type: Maintenance

#253 Add mining pool
  imports/startup/client/mining-pools.js
Labels: Priority: Low, Status: Completed, Type: Maintenance

#255 MINING_POOLS export fix
  imports/startup/client/mining-pools.js
Labels: Priority: Critical, Status: Completed, Type: Bug

#257 MINING_POOLS export fix
  imports/startup/client/mining-pools.js
Labels: Priority: Critical, Status: Completed, Type: Bug
